### ISSUE TITLE
v2 upgrade docs

### ISSUE THREAD

**Issue by kevinkuszyk** [NHSDigital/nhsuk-react-components#103]
@Tomdango i just noticed we have some docs for upgrading from 0.x to 1.x.  I guess we should do the same for 1.x to 2.x?

It looks like it's just the panel and promo that we've depreciated.  I can make a start on some docs for those.

And how do feel about adding a docs folder and having them as markdown files in there?  If yes, I'll open a PR to move the 1.x upgrade docs over.

---

List of changes to include:

- [ ] existing upgrade doc in change log
- [ ] #108

**Comment by Tomdango** [comment]
I've merged the pull request to add the docs folder - leaving this issue open to cover docs for V2.
