### ISSUE TITLE
Input type=number / DateInput wheel scroll behaviour

### ISSUE THREAD

**Issue by frobernik** [NHSDigital/nhsuk-react-components#107]
Hi there,

We've upgraded to the 2.0.0-beta.1 and have noticed some strange behaviour with the `<Input type="number"/>` and `<DateInput/>` components. When focused on an input field (that has a type of number) the browser window scrolls and the focused field increments/decrements as well.

Input type=number
![NumberBox](https://user-images.githubusercontent.com/632231/131859576-4d7512a3-c868-4871-a9da-c2e824456e9a.gif)

DateInput
![DateInput](https://user-images.githubusercontent.com/632231/131859530-5e34a2a3-a826-4a04-9ede-b2879c4ea2a5.gif)

However on the NHSUK react components library site the DateInput component is only allowing the browser window to be scrolled
![NHSUKReactComponents](https://user-images.githubusercontent.com/632231/131865026-2abff9ea-767a-4fab-8d39-17cc97632617.gif)

Is this a prop we're missing, some code we need to add or is it a bug in nhs-react-components?

Thanks,
Jacob

**Comment by KaiSpencer** [comment]
Hi @frobernik,
There were some changes missed in a previous PR.
I have raised #108 to fix this issue. 

Can you confirm you are using React 17.x, I could only replicate this ^17.

**Comment by frobernik** [comment]
We are indeed on react ^17 (17.0.2 TBP)

**Comment by Tomdango** [comment]
I personally don't like the idea of switching the Input to a type of text, as that would allow any text to be entered and potentially additional client-side changes to only allow number characters.
I believe the reason why the scrolling behaviour happens is when there is no event handlers on the input, so the browser defaults to it's default behaviour (change on scroll).

Could you try using this sample instead:
```jsx
<DateInput>
    <DateInput.Day onWheel={(e) => e.target.blur()} />
    <DateInput.Month onWheel={(e) => e.target.blur()} />
    <DateInput.Year onWheel={(e) => e.target.blur()} />
</DateInput>
```

**Comment by KaiSpencer** [comment]
> I personally don't like the idea of switching the Input to a type of text, as that would allow any text to be entered and potentially additional client-side changes to only allow number characters.
> I believe the reason why the scrolling behaviour happens is when there is no event handlers on the input, so the browser defaults to it's default behaviour (change on scroll).
> 
> Could you try using this sample instead:
> 
> ```js
> <DateInput>
>     <DateInput.Day onWheel={(e) => e.target.blur()} />
>     <DateInput.Month onWheel={(e) => e.target.blur()} />
>     <DateInput.Year onWheel={(e) => e.target.blur()} />
> </DateInput>
> ```

Whilst this is one solution, the browser loses focus of the input if the scroll wheel is used, is this a good idea from an accessibility point of view if for example the input is navigated to via tab.

**Comment by Tomdango** [comment]
If the input is navigated to by tab, a user would have to scroll over the field using the scroll wheel to hit this event, so shouldn't affect any keyboard users. However, I would be happy with the original approach to fix this issue - thanks for the links and info @KaiSpencer!

**Comment by frobernik** [comment]
I thought I'd do a bit more detective work and I think I've found what might be the issue :-

React 16.14.0 behaviour
![React-16 14 0](https://user-images.githubusercontent.com/632231/132538483-e45ba827-8c4b-40d6-8b95-11f224db7760.gif)

React 17.0.2 behaviour
![React-17 0 2](https://user-images.githubusercontent.com/632231/132539245-6340529c-9620-4fba-ae15-b3a902c3ec39.gif)

It seems like touch and wheel events have been altered in React 17+ as discussed in https://github.com/facebook/react/issues/19651 .

I'm currently testing a workaround that gets our `<Input type="number">` close to the React 16.14.0 behaviour.
