### ISSUE TITLE
Deprecated import does not work

### ISSUE THREAD

**Issue by smaldon-bjss** [NHSDigital/nhsuk-react-components#113]
The upgrading to 2.0 guide implies I can import the deprecated components here.

> The Panel and Promo components have been removed from nhsuk-frontend since version 4.0.0. As a result, we have deprecated these components. These components work exactly as they did before, with the only difference being a slightly different import.

`import { Panel, Promo } from "nhsuk-react-components/deprecated";`

However when I try to apply this it seems that I get an error extract like so

`Module not found: Can't resolve 'nhsuk-react-components/deprecated'`

I believe this is related to what looks like might be a mistake in `rollup.config.js` where `input: 'src/index.ts'` is specified for both the components output to `packageJson.main` and `'dist/deprecated.js'`.

Would it be possible to amend or work around this? Upgrading to 2.0.0 seems difficult in a codebase that makes multiple references to those deprecated components in multiple ways that bespokely modify the style to look like cards and my ideal strategy would be to start by importing the deprecated components then move things over one by one in much more manageable smaller pieces of work.

**Comment by kevinkuszyk** [comment]
Hello @smaldon-bjss 👋,

Is it just a typo in the docs?  This seems to work for me:

```
import { Panel, Promo } from 'nhsuk-react-components/dist/deprecated';
```

If the bug is in fact with our rollup config, a PR with the fix would be most welcome!

**Comment by smaldon-bjss** [comment]
Hi @kevinkuszyk, long time no see :)

I tried this but now I'm back to square one with regards to `Promo` being defined as null the first time my code gets to one of the deprecated objects.

```
import { Promo } from 'nhsuk-react-components/dist/deprecated';
...
          <Promo.Group>
```

returns the error `TypeError: Cannot read property 'Group' of undefined`

My trouble is that I'm not sure how to do local development with the library and prove that any changes work or if my theory about the rollup configuration is a good one. Can you at least look at it and tell me if you think it looks right or wrong?

**Comment by smaldon-bjss** [comment]
Actually if I changed these lines
```
import { Col, Container, Row, ActionLink } from 'nhsuk-react-components';
import { Promo } from 'nhsuk-react-components/dist/deprecated'
```
to this
```
import { Col, Container, Row, ActionLink } from 'nhsuk-react-components/dist/deprecated';
import { Promo } from 'nhsuk-react-components/dist/deprecated'
```

and my code looks like this
```
function Index({
...
}: PropTypes): JSX.Element {
  return (
    <Container>
      <Row>
        <Col width="full">
          <PageHeading pageTitle="Welcome to xxxxxxxxxxxxxx" />
          <Promo.Group>
```

shouldn't I have expected it to fail on the `<Container>` tag? I still get the same error about `Cannot read property 'Group' of undefined` which is making me think `nhsuk-react-components/dist/deprecated` behaves exactly the same as `nhsuk-react-components` which is what I'd expect if my reading of the rollup configuration is correct. I'm just not sure what it's _supposed_ to be or how to try anything.

**Comment by ramyas16** [comment]
yea sure

**Comment by ramyas16** [comment]
@smaldon-bjss You are right, it is to do with rollup.config.js

Created a pull request to fix this. 
https://github.com/NHSDigital/nhsuk-react-components/pull/115

However, I found another issue while using `Promo` like below, it throws hook errors in console [please see below screenshot]. This is an example code from storybook and it does not occur while running storybook, i don't know the reason yet.   I will raise a separate issue after taking to @Tomdango about this. 

``` 
<Promo
        href="https://www.nhs.uk"
        imageSrc="https://assets.nhs.uk/prod/images/MS_1018_give_blood.2e16d0ba.fill-2400x1350.jpg"
        imageProps={{ alt: '' }}
      >
        <Promo.Heading>Save a life: give blood</Promo.Heading>
        <Promo.Description>
          Please register today. Donating blood is easy, and saves lives.
        </Promo.Description>
      </Promo> 

```

![Screenshot 2022-03-23 at 16 38 58](https://user-images.githubusercontent.com/53491351/159750755-d65195c0-1460-4e2f-a8de-b7982ab7b8d6.png)

**Comment by kevinkuszyk** [comment]
@smaldon-bjss we've fixed the rollup config and the docs.  v2.1 should be up on npm shortly with the fixes.

Thanks to @ramyas16 for fixing.
