### ISSUE TITLE
Accessibility issues with radio buttons

### ISSUE THREAD

**Issue by sarahrose-ferris1-NHSD** [NHSDigital/nhsuk-react-components#127]
An issue was flagged in our accessibility audit, wherein the **role=radiogroup** attribute that is automatically assigned to radio components prevents the screen reader from associating the buttons with the fieldset legend. This results in the screen reader does not pick up the legend, which means their meaning unclear to the user. When this role is changed to "none", the issue is resolved (see screenshots below). 

**Extract from Accessibility Audit:** 
![image](https://user-images.githubusercontent.com/113982375/204783802-0d7c069c-935c-428e-aaa6-903cc2f4d356.png)

**Role="none":**
![image](https://user-images.githubusercontent.com/113982375/204783880-afacc9cf-130d-4c05-bbed-f7c5c682958e.png)

**Role="radiogroup":**
![image](https://user-images.githubusercontent.com/113982375/204783987-54036650-b78e-43b3-bf5f-77815d4bfd76.png)

**Comment by Tomdango** [comment]
Fixed in #131
