### ISSUE TITLE
A-Z List Panel styling doesn't match styleguide

### ISSUE THREAD

**Issue by waringr** [NHSDigital/nhsuk-react-components#136]
The styling of the list-panel component https://nhsdigital.github.io/nhsuk-react-components/?path=/docs/components-listpanel--standard doesn't match the styling in the styleguide https://service-manual.nhs.uk/design-system/patterns/a-to-z-page#a-to-z-list-panel

**Comment by kevinkuszyk** [comment]
@waringr thanks for reporting.  Do you have the bandwidth to fix in a PR?

**Comment by KaiSpencer** [comment]
List panel and Nav A-Z were [removed in 6.0.0](https://github.com/nhsuk/nhsuk-frontend/blob/cf43748b79f0f1bb63578e97f07ab0301a073e3d/CHANGELOG.md#600---29-november-2021). 

So I don't think we should make any changes here other than deprecating the ListPanel _and_ NavAZ

Whilst they are removed as components they are still included as [patterns](https://service-manual.nhs.uk/design-system/patterns) so I think we need to consider how we do or don't want to support patterns too.

**Comment by ItsiAdam** [comment]
> List panel and Nav A-Z were [removed in 6.0.0](https://github.com/nhsuk/nhsuk-frontend/blob/cf43748b79f0f1bb63578e97f07ab0301a073e3d/CHANGELOG.md#600---29-november-2021).
> 
> So I don't think we should make any changes here other than deprecating the ListPanel _and_ NavAZ
> 
> Whilst they are removed as components they are still included as [patterns](https://service-manual.nhs.uk/design-system/patterns) so I think we need to consider how we do or don't want to support patterns too.

Perhaps in addition to deprecating them here, patterns could be made a part of the [extensions](https://github.com/NHSDigital/nhsuk-react-components-extensions) library?


Along the same train of thought, things like page headings would be useful to have as components. A page heading component could take a title and optionally a caption. I've made a component like this already for an internal/personal project I'm working on, but I haven't made a pull request as I figured it didn't fit in either library.

**Comment by KaiSpencer** [comment]
> > List panel and Nav A-Z were [removed in 6.0.0](https://github.com/nhsuk/nhsuk-frontend/blob/cf43748b79f0f1bb63578e97f07ab0301a073e3d/CHANGELOG.md#600---29-november-2021).
> > So I don't think we should make any changes here other than deprecating the ListPanel _and_ NavAZ
> > Whilst they are removed as components they are still included as [patterns](https://service-manual.nhs.uk/design-system/patterns) so I think we need to consider how we do or don't want to support patterns too.
> 
> Perhaps in addition to deprecating them here, patterns could be made a part of the [extensions](https://github.com/NHSDigital/nhsuk-react-components-extensions) library?
> 
> Along the same train of thought, things like page headings would be useful to have as components. A page heading component could take a title and optionally a caption. I've made a component like this already for an internal/personal project I'm working on, but I haven't made a pull request as I figured it didn't fit in either library.

Hey Adam,

Whilst patterns aren't strictly components, they are included in the service manual, so I believe they can be included in this library alongside components. For example [here](https://github.com/NHSDigital/nhsuk-react-components/pull/138) with the ReviewDate that we have lined up for v5. IMO its better if we can provide easy component imports like this, and I think cases like this where they are specifically referenced in the service manual are fine to include. 

I agree regarding your point about headings and other convenience components like this, feel free to open PR's into the extensions library for any components like this and we can take a look.

**Comment by jakeb-nhs** [comment]
This has received some attention as part of the latest release: https://github.com/NHSDigital/nhsuk-react-components/releases/tag/v4.0.0
See the guidance here about NavAZ and ListPanel https://github.com/NHSDigital/nhsuk-react-components/blob/feature/nhsuk-frontend-v8/docs/upgrade-to-4.0.md#navaz-and-listpanel
