### ISSUE TITLE
Storybook not loading

### ISSUE THREAD

**Issue by wozzo** [NHSDigital/nhsuk-react-components#161]
Attempts to load the [storybook](https://nhsdigital.github.io/nhsuk-react-components/) result in the following error appearing on the page.

```
Failed to fetch dynamically imported module: https://nhsdigital.github.io/nhsuk-react-components/assets/preview-bb5acd95.js
TypeError: Failed to fetch dynamically imported module: https://nhsdigital.github.io/nhsuk-react-components/assets/preview-bb5acd95.js
```
![image](https://user-images.githubusercontent.com/6189323/231135740-5476812c-3b4b-4dfa-aaf3-2573150ebac9.png)

This is caused by a failure to load the `_commonjsHelpers-042e6b4d.js` file the cause of which is talked about in this [storybook issue](https://github.com/storybookjs/storybook/issues/20564#issuecomment-1385326683).

**Comment by wozzo** [comment]
#160 attempted to fix, but because the storybook build runs a clean the created file gets wiped.

I think changing [this line](https://github.com/NHSDigital/nhsuk-react-components/blob/9dc9b614e68ac4641d87c799876065e5ea245818/.github/workflows/storybook.yml#L21) to 

```
run: yarn build-storybook -- -o ./storybook-build  && echo '' > ./storybook-build/.nojekyll && yarn storybook-to-ghpages --ci --existing-output-dir ./storybook-build
```
should yield the desired effect.

**Comment by KaiSpencer** [comment]
Thanks @wozzo 

We are in the process of setting up Chromatic for hosting and preview deployments etc.

For now [https://6422e711d7f854c1b681c505-gucnykxpfl.chromatic.com/?path=/docs/welcome--docs](this link) is a published version of the current main build

**Comment by wozzo** [comment]
Great cheers.
