### ISSUE TITLE
Warning message colour does not pass WCAG AAA 7:1 contrast ration

### ISSUE THREAD

**Issue by jakewalker4** [NHSDigital/nhsuk-react-components#169]
![image](https://github.com/NHSDigital/nhsuk-react-components/assets/104999113/7beb5ca3-ff69-4e5b-841e-da637c8de1af)

**Comment by KaiSpencer** [comment]
Hi @jakewalker4 thanks for raising this issues around AAA compliance.

Unfortunately, these will need to move to the [NHSUK Frontend](https://github.com/nhsuk/nhsuk-frontend/issues) repo, as we do not add any styling to any components. We simply use the classes directly as provided by the nhsuk-frontend library.

Any colour changes to meet AAA compliance will need to be made in that repository.
