### ISSUE TITLE
Grey text colour does not pass WCAG AAA 7:1 contrast ration

### ISSUE THREAD

**Issue by jakewalker4** [NHSDigital/nhsuk-react-components#171]
![image](https://github.com/NHSDigital/nhsuk-react-components/assets/104999113/89bf7918-22d6-4f50-af70-dfd07c606203)

**Comment by KaiSpencer** [comment]
Hi @jakewalker4 thanks for raising this issues around AAA compliance.

Unfortunately, these will need to move to the [NHSUK Frontend](https://github.com/nhsuk/nhsuk-frontend/issues) repo, as we do not add any styling to any components. We simply use the classes directly as provided by the nhsuk-frontend library.

Any colour changes to meet AAA compliance will need to be made in that repository.
