### ISSUE TITLE
JS doesn't seem to be loading for specific components

### ISSUE THREAD

**Issue by kurtisRogers-Nomensa** [NHSDigital/nhsuk-react-components#181]
Hi all,

Love what you've put together :heart: but having a little trouble getting the Header component to appear correctly in my Storybook instance. I think the radios* are also having a little trouble as well.

The basic header example:
![image](https://github.com/NHSDigital/nhsuk-react-components/assets/118725785/46ab514a-d5bf-403a-91f9-eb2f9085a3b4)

I've imported all of the styles (core and NHSUK):
```scss
@import '../node_modules/nhsuk-frontend/packages/core/all.scss';

@import '../node_modules/nhsuk-frontend/packages/nhsuk.scss';
```

I've created an importer for the components here:
```js
import {
  ActionLink, 
  ArrowLeftIcon,
  ArrowRightCircleIcon, 
  ArrowRightIcon, 
  BackLink,
  BodyText,
  Breadcrumb,
  Button, 
  ButtonLink, 
  Card, 
  CareCard, 
  Checkboxes,
  ChevronLeftIcon, 
  ChevronRightIcon, 
  Clearfix, 
  CloseIcon,
  Col,
  Container,
  ContentsList, 
  CrossIcon, 
  DateInput, 
  DefaultButton, 
  Details, 
  DoDontList, 
  EmdashIcon, 
  ErrorMessage, 
  ErrorSummary, 
  Fieldset, 
  Footer, 
  Form, 
  Header, 
  Hero, 
  Hint, 
  Icons, 
  Images, 
  Input, 
  InsetText, 
  Label, 
  LedeText, 
  ListPanel, 
  MinusIcon, 
  NavAZ, 
  Pagination, 
  PlusIcon, 
  Radios, 
  ReadingWidth, 
  ReviewDate, 
  Row, 
  SearchIcon, 
  Select, 
  SkipLink, 
  SmallEmdashIcon, 
  SummaryList, 
  Table, 
  Tag, 
  Textarea, 
  TickIcon, 
  WarningCallout, 
  useFormContext
} from 'nhsuk-react-components';

export {
  ActionLink as NHSActionLink, 
  ArrowLeftIcon as NHSArrowLeftIcon,
  ArrowRightCircleIcon as NHSArrowRightCircleIcon, 
  ArrowRightIcon as NHSArrowRightIcon, 
  BackLink as NHSBackLink,
  BodyText as NHSBodyText,
  Breadcrumb as NHSBreadcrumb,
  Button as NHSButton, 
  ButtonLink as NHSButtonLink, 
  Card as NHSCard, 
  CareCard as NHSCareCard, 
  Checkboxes as NHSCheckboxes,
  ChevronLeftIcon as NHSChevronLeftIcon, 
  ChevronRightIcon as NHSChevronRightIcon, 
  Clearfix as NHSClearfix, 
  CloseIcon as NHSCloseIcon,
  Col as NHSCol,
  Container as NHSContainer,
  ContentsList as NHSContentsList, 
  CrossIcon as NHSCrossIcon, 
  DateInput as NHSDateInput, 
  DefaultButton as NHSDefaultButton, 
  Details as NHSDetails, 
  DoDontList as NHSDoDontList, 
  EmdashIcon as NHSEmdashIcon, 
  ErrorMessage as NHSErrorMessage, 
  ErrorSummary as NHSErrorSummary, 
  Fieldset as NHSFieldset, 
  Footer as NHSFooter, 
  Form as NHSForm, 
  Header as NHSHeader, 
  Hero as NHSHero, 
  Hint as NHSHint, 
  Icons as NHSIcons, 
  Images as NHSImages, 
  Input as NHSInput, 
  InsetText as NHSInsetText, 
  Label as NHSLabel, 
  LedeText as NHSLedeText, 
  ListPanel as NHSListPanel, 
  MinusIcon as NHSMinusIcon, 
  NavAZ as NHSNavAZ, 
  Pagination as NHSPagination, 
  PlusIcon as NHSPlusIcon, 
  Radios as NHSRadios, 
  ReadingWidth as NHSReadingWidth, 
  ReviewDate as NHSReviewDate, 
  Row as NHSRow, 
  SearchIcon as NHSSearchIcon, 
  Select as NHSSelect, 
  SkipLink as NHSSkipLink, 
  SmallEmdashIcon as NHSSmallEmdashIcon, 
  SummaryList as NHSSummaryList, 
  Table as NHSTable, 
  Tag as NHSTag, 
  Textarea as NHSTextarea, 
  TickIcon as NHSTickIcon, 
  WarningCallout as NHSWarningCallout, 
  useFormContext
}
```

Could it have something to do with the way I've imported them?

Appreciate any advice/guidance on this!

**Comment by KaiSpencer** [comment]
Hey @kurtisRogers-Nomensa,

Your imports look fine, we have a current outstanding issue #178 

Can you confirm what version of the nhsuk-frontend you have installed?

**Comment by kurtisRogers-Nomensa** [comment]
Hey @KaiSpencer!

Thanks for getting back to me, really appreciate it! 

Sorry, should've listed that stuff above! 

![image](https://github.com/NHSDigital/nhsuk-react-components/assets/118725785/3cb90ca7-d275-494d-840f-d151fbe9cb44)

**Comment by KaiSpencer** [comment]
> Hey @KaiSpencer!
> 
> Thanks for getting back to me, really appreciate it!
> 
> Sorry, should've listed that stuff above!
> 
> ![image](https://user-images.githubusercontent.com/118725785/274260763-3cb90ca7-d275-494d-840f-d151fbe9cb44.png)

Could you try nhsuk-frontend with a value of ^4, just to see if its related to #178

**Comment by kurtisRogers-Nomensa** [comment]
Just gave it and it's a darmatic improvement:
![image](https://github.com/NHSDigital/nhsuk-react-components/assets/118725785/3d14f7ca-8190-4e0d-8ff4-d925650c167f)

Should I move forward with this for now, keep an eye on https://github.com/NHSDigital/nhsuk-react-components/issues/178  and upgrade when it's all good?

**Comment by KaiSpencer** [comment]
Yeah, move forward with that for now. And hopefully soon we can support the later versions and their features/fix the breaking changes that caused the issue above.

We have a branch with v5 of the nhsuk-frontend just about there, after that we can work on the next few versions. 

Unfortunately nobody gets paid or time to work on this project, so it is just best effort from the current list of maintainers in our free time.

I will close this for now with pinning to ^4 as a workaround.

**Comment by kurtisRogers-Nomensa** [comment]
Thanks @KaiSpencer, really appreciate it! 

I need to get this project underway but it's hightime I actually contributed to an OS project. I'll look to get a message over to you guys to try and support on the project in the near future. 

Thanks again! ❤️
