### ISSUE TITLE
Buttons are missing data attribute

### ISSUE THREAD

**Issue by edwardhorsford** [NHSDigital/nhsuk-react-components#218]
The buttons in the NHS design system include a data attribute that seems to be missing from the buttons shown in the storybook examples.

[Example from the design system](https://service-manual.nhs.uk/design-system/components/buttons):
```html
<button class="nhsuk-button" data-module="nhsuk-button" type="submit">
  Save and continue
</button>
```

Example from storybook:
```html
<button class="nhsuk-button" aria-disabled="false" type="submit">Primary</button>
```

**Comment by Tomdango** [comment]
Fixed by https://github.com/NHSDigital/nhsuk-react-components/pull/231
