### ISSUE TITLE
React Router doesn't appear to be compatible with the header links.

### ISSUE THREAD

**Issue by charlesomer** [NHSDigital/nhsuk-react-components#49]
There appears to be no easy way to use React Router with the header links/styles of this repo. 

For example, `<Link to='/page' component={Header.NavItem}>Page</Link>` doesn't do the trick and there doesn't seem to be a way to pass the React Router NavLink/Link component to `Header.NavItem` unlike in Bootstrap or MaterialUI for example.

**Comment by charlesomer** [comment]
For now I'm using [wouter](https://github.com/molefrog/wouter) instead of react-router since you can wrap a wouter link but this can cause issues later down the road since wouter doesn't implement everything that react-router does :(

**Comment by Tomdango** [comment]
Hi Charles, I mentioned about using the history object in https://github.com/NHSDigital/nhsuk-react-components/issues/51 to use React Router with the Header component. However, I think it is a good idea to be able to pass the React Router Link component to the `Header.NavItem` and `Header.Logo` components, as using React Router in this way is a very common use case.

**Comment by charlesomer** [comment]
Yeah it would be nice if it was possible to pass the react router component to the header (for the nav items as well as the logo/service name). I believe react router has specific links for the nav too.

**Comment by lukepearson** [comment]
It would be very nice if other places that used links could have that behaviour too.
As already mentioned:
* Header.Logo
* Header.NavItem

Additionally:
* NavAZ.LinkItem
* BackLink
* ActionLink
* Breadcrumb
* Promo
* ListPanel -> currently uses backToTopLink, not sure if this needs an option to use `window.scrollTo(0, 0)` instead?

**Comment by Tomdango** [comment]
Closing this as fixed as part of https://github.com/NHSDigital/nhsuk-react-components/pull/54/files
