### ISSUE TITLE
Panel with a label has no css at `nhsuk-frontend/dist/nhsuk.css`

### ISSUE THREAD

**Issue by charlesomer** [NHSDigital/nhsuk-react-components#53]
Just tried to use a panel component with a label but it seems the required css isn't present in `nhsuk-frontend` anymore? It also doesn't seem to appear on the service manual website. Has this been removed?

**Comment by nbetts** [comment]
The panel and promo components have been superseded by the new card component in `nhsuk-frontend v4.0.0`. Since this library hasn't been updated to use it yet, you should reference version `3.0.0` or `3.1.0` as a peer dependency to use panels.

**Comment by charlesomer** [comment]
Ah right okay, hopefully this library gets updated soon :)

**Comment by Tomdango** [comment]
Hi Charles, I've been working on the uplift to the latest version of `nhsuk-frontend` but I've been super busy lately! I've got most of the changes implemented, it's just the process of checking for regression against `nhsuk-frontend` to make sure that we stay aligned :)

**Comment by charlesomer** [comment]
Fantastic! I look forward to it 😄 I would try to help but unfortunately I'm stuck doing university work most of the time at the moment 😢

**Comment by kevinkuszyk** [comment]
@charlesomer we shipped a beta this week which includes the new card component.  apologies for the time it's taken to get an update out.

Fyi - we're running the beta with the lastest nhsuk-frontend css in our app.

With that in mind, I'm going to close this issue.
