### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by jenbutongit** [NHSDigital/nhsuk-react-components#72]
Hey Team,

this API is awesome!! 

I'm currently working on [a product which can configure/create forms via a react GUI]( https://github.com/XGovFormBuilder/digital-form-builder). The current govuk react libraries out there are either incomplete, outdated or have a njks based API. I'm planning on (hard) forking this project for a nicer govuk react developer experience. All seems to work ok! I quickly tested out in this repo https://github.com/CautionYourBlast/nhsuk-govuk-react which re-compiles your dist/lib and replaces nhsuk with govuk. The markup is mostly all there and can be styled correctly. 

I'll keep an eye out on the issues list. I'd be happy to contribute (depending on capacity..!). Thanks again!

**Comment by Tomdango** [comment]
Hi, 

Thanks for the feedback!! It's well appreciated :smile:. I've had a little look at the repo and it looks good, the NHS.UK components and GOV.UK components are very similar so I'm not surprised if it works quite well! Good luck with the project and if you've got any questions feel free to ask :slightly_smiling_face:
