### ISSUE TITLE
Time Component

### ISSUE THREAD

**Issue by gurvinderpsg** [NHSDigital/nhsuk-react-components#91]
For our Project we have a requirement for Time Component to record the Time along with the date. Is there any component that exists and can be used for Time?

**Comment by kevinkuszyk** [comment]
ping @Tomdango 

This is going to be used on Forms - @gurvinderpsg is leading one of our squads

/cc @zeshan-zoheb1 @ramyas16

**Comment by lukepearson** [comment]
Hi @gurvinderpsg, this project is pretty much a pure implementation of the nhsuk-frontend in React, which includes the componts listed here https://github.com/nhsuk/nhsuk-frontend/tree/master/app/components

I suspect that new components which aren't a part of the nhsuk-fontend kit will have to be added to the extensions library 
https://github.com/NHSDigital/nhsuk-react-components-extensions/

**Comment by gurvinderpsg** [comment]
Thanks Luke,

can you please elaborate on the process of adding it to the extension library?

Thanks!!

**Comment by Tomdango** [comment]
Hi @gurvinderpsg,

There's an nhsuk-react-components-extensions repository [here](https://github.com/NHSDigital/nhsuk-react-components-extensions/). If you'd like to include a time component, feel free to create an issue or raise a merge request to get it merged into there!
