### ISSUE TITLE
Focus behaviour for <Button> and <Footer> links

### ISSUE THREAD

**Issue by frobernik** [NHSDigital/nhsuk-react-components#95]
# Bug Report

## What is the issue?

The yellow focus indicator is visible after clicking on a <Button> or a <Footer> link.

### Mouse click
Move the mouse over the button, click and then move the mouse away. The yellow highlight is shown on the button.
![mouseFocusAndClick](https://user-images.githubusercontent.com/632231/123977188-ae829200-d9b6-11eb-9d32-edb02480c932.gif)

### Keyboard
Tab onto the button, tap the enter key and leave. The yellow highlight is shown on the button.
![keyboardFocusAndEnter](https://user-images.githubusercontent.com/632231/123977249-bcd0ae00-d9b6-11eb-9478-25661d8f1a56.gif)

## What was the environment where this issue occurred?

* Device: Mac
* Operating System: OSX Big Sur 11.4
* Browser: Chrome
* Browser version: 91.0.4472.106 (Official Build) (x86_64)
* NHS.UK frontend package version: nhsuk-react-components v1.2.4
* Node version: v14.17.0
* npm version: v6.14.3

## Is there anything else you think would be useful in recreating the issue?

We're aware this could be an accessibility feature and would like some input (no pun intended) on whether the behaviour is different in more recent versions or whether its the same?

**Comment by kevinkuszyk** [comment]
@Tomdango linking to the upstream issue: nhsuk/nhsuk-frontend#751.

**Comment by kevinkuszyk** [comment]
@frobernik I guess we can close this issue if this is in fact the correct behaviour at the moment?

**Comment by frobernik** [comment]
It certainly is and closing
