### ISSUE TITLE
Missing github release for 1.2.8

### ISSUE THREAD

**Issue by kevinkuszyk** [NHSDigital/nhsuk-react-components#96]
Hi @Tomdango 

It looks like you forgot to tag 1.2.8 release.  Would you mind to tag it when you have a minute?  I'm trying to work out the diff between that and the previous version and GitHub doesn't make it easy with just the commit hashes.

Thanks!

**Comment by Tomdango** [comment]
Hi @kevinkuszyk - I'll see if I can add a tag at the commit hash for 1.2.8, but there have been merges to main since then so not sure if it can be easily don!

**Comment by kevinkuszyk** [comment]
Something like this should do it:

```
git tag -a v1.2 9fceb02 -m "Message here"
```

https://stackoverflow.com/a/4404197/1288481

**Comment by kevinkuszyk** [comment]
Closing now that we've shipped the beta.
