### ISSUE TITLE
Card Component

### ISSUE THREAD

**Issue by ramyas16** [NHSDigital/nhsuk-react-components#97]
I am trying to use the Card component and throws the below error. 

Failed to compile:
Attempted import error: 'Card' is not exported from 'nhsuk-react-components'

I can see, It's definitely exported `export { default as Card } from './components/card'; ` and also it definitely works in the storybook, Any thoughts?

versions: 

nhsuk-react-components - 1.2.8
nhsuk-frontend: 4.1.0

**Comment by kevinkuszyk** [comment]
@ramyas16 it's in `2.0.0-beta.1` which we shipped yesterday.
